# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l

  auto:
    desc: do it all idempotent
    aliases:
      - all
    cmds:
      - task: clean
      - task: setup-git
      - task: git-sync
      - task: archive-current
      - task: clean

  git-sync:
    desc: sync most recent data from github.com/deadlock-wiki/deadbot
    aliases:
      - s
    cmds:
      - task: archive-current
      - mkdir -p ./data/current && rm -rf ./data/current/*
      - cp -a ./deadbot/output-data/* ./data/current

  changelogs-sync:
    desc: use docker and deadbot to fetch latest changelogs
    cmds:
      - task: archive-current
      - docker pull ghcr.io/deadlock-wiki/deadbot:latest
      - docker run -e CHANGELOGS=True -v ./data/current:/output -v ./inputs/raw_changelogs:/input/raw-changelogs ghcr.io/deadlock-wiki/deadbot:latest

  setup-git:
    - git clone git@github.com:deadlock-wiki/deadbot.git ./deadbot
  
  clean:
    desc: Cleanup temp files
    aliases:
      - c
    cmds:
      - rm -rf ./deadbot

  generate:
    desc: generate charts from data
    aliases:
      - g
      - gen
    cmds:
      - ls

  archive-current:
    desc: Copy current game data into archive folder
    aliases:
      - a
    vars:
      REV:
        # trim CR (0x15) from CRLF line endings
        sh: cat ./data/current/version.txt | tr -d '\015' | awk -F "=" '/SourceRevision/ {print $2}'
      DATE:
        sh: cat ./data/current/version.txt | tr -d '\015' | awk -F "=" '/VersionDate/  {gsub(" ","_",$2); print $2}'
    cmds:      
      - mkdir -p "./data/archive/{{.REV}}_{{.DATE}}"
      - cp -a ./data/current/* "./data/archive/{{.REV}}_{{.DATE}}"