on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"
  push:
    branches: 
      - "main"
jobs:
  deadbot-sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        # https://taskfile.dev/installation/#github-actions
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone Deadbot repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        # https://github.com/marketplace/actions/clone-github-repo-action
        with:
          depth: 1
          branch: 'master'
          owner: 'deadlock-wiki'
          repository: 'deadbot'
      - run: task sync
      - run: task archive-current
      - run: grep 'SourceRevision' ./data/current/version.txt >> "$GITHUB_ENV"
      - uses: actions4git/add-commit-push@v1
        with:
          commit-committer: '${{github.actor}}'
          commit-message: 'Revision $GAME_VER - ${{github.workflow}} - ${{github.event_name}} - ${{githuv.run_number}}'
