on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"
  push:
    branches: "main"
jobs:
  job:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          brew update
          brew install go-task
      - run: task auto
      - uses: actions4git/add-commit-push@v1
