on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"
  push:
    branches: "main"
jobs:
  deadbot-sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task auto
      - uses: actions4git/add-commit-push@v1
